server:
  port: 9090
spring:
  application:
    name: rabitmqSender
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: testhost
    connection-timeout: 1200
    publisher-confirms: true # 开启发送确认
    publisher-returns: true # 开启发送失败退回
    template:
          mandatory: true #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
    listener:
#      direct:
#        acknowledge-mode: manual   # 开启ACK
      simple:
        acknowledge-mode: manual   # 开启ACK