server:
  port: 9091
spring:
  application:
    name: rabitmqDemo
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: testhost
#    publisher-confirms: true # 开启发送确认
#    publisher-returns: true # 开启发送失败退回
    listener:
#      direct:
#        acknowledge-mode: manual   # 开启ACK
      simple:
        acknowledge-mode: manual # 开启ACK
        concurrency: 1  #消费者最小数量
        max-concurrency: 4 #消费者最大数量
        prefetch: 2 #在单个请求中处理的消息个数，应该大于等于事务数量(unack的最大数量)