server:
  port: 8082
spring:
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0
  zipkin:
      base-url: http://localhost:9411/
  application:
    name: service-hi
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
